<?xml version="1.0" encoding="utf-8"?><Database Name="XSKT" Class="XSKTDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-ET1GGIC\SQLEXPRESS;Initial Catalog=XSKT;Integrated Security=True" SettingsObjectName="XSKTDB.Properties.Settings" SettingsPropertyName="XSKTConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.LocationPrizes" Member="LocationPrizes">
    <Type Name="LocationPrize">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="LocationPrize_PrizeDetail" Member="PrizeDetails" ThisKey="ID" OtherKey="LoctionPrizeId" Type="PrizeDetail" />
    </Type>
  </Table>
  <Table Name="dbo.Prizes" Member="Prizes">
    <Type Name="Prize">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstPrize" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SecondPrize" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ThirdPrize" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FourthPrize" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FifthPrize" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SixthPrize" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SeventhPrize" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SpecialPrize" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Prize_PrizeDetail" Member="PrizeDetails" ThisKey="ID" OtherKey="PrizeId" Type="PrizeDetail" />
    </Type>
  </Table>
  <Table Name="dbo.PrizeDetails" Member="PrizeDetails">
    <Type Name="PrizeDetail">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PrizeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LoctionPrizeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DatePrize" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="LocationPrize_PrizeDetail" Member="LocationPrize" ThisKey="LoctionPrizeId" OtherKey="ID" Type="LocationPrize" IsForeignKey="true" />
      <Association Name="Prize_PrizeDetail" Member="Prize" ThisKey="PrizeId" OtherKey="ID" Type="Prize" IsForeignKey="true" />
    </Type>
  </Table>
</Database>